import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { tanstackRouter } from '@tanstack/router-plugin/vite'
import { VitePWA } from 'vite-plugin-pwa'
import { sriWorkboxPlugin } from './src/client/lib/sri-workbox-plugin'
import path from 'path'

import { copyFileSync, existsSync, mkdirSync, readFileSync } from 'fs'

/**
 * Copy @wireapp/core-crypto WASM to the build output.
 *
 * The crypto-worker uses `new URL("core-crypto-ffi_bg.wasm", import.meta.url)`
 * to load the WASM module at runtime. Vite cannot resolve this at build time
 * because the reference is inside a dynamically-imported node_modules package
 * in a Web Worker context. This plugin copies the WASM file alongside the
 * worker chunk so the runtime URL resolves correctly.
 */
function coreCryptoWasmPlugin(): Plugin {
  return {
    name: 'core-crypto-wasm-copy',
    writeBundle(options) {
      const wasmSrc = path.resolve(
        __dirname,
        'node_modules/@wireapp/core-crypto/src/autogenerated/core-crypto-ffi_bg.wasm'
      )
      if (!existsSync(wasmSrc)) return

      const outDir = options.dir ?? path.resolve(__dirname, 'dist/client')
      const assetsDir = path.resolve(outDir, 'assets')
      if (!existsSync(assetsDir)) mkdirSync(assetsDir, { recursive: true })

      const wasmDest = path.resolve(assetsDir, 'core-crypto-ffi_bg.wasm')
      copyFileSync(wasmSrc, wasmDest)
    },
  }
}

function cspNoncePlaceholderPlugin(): Plugin {
  return {
    name: 'csp-nonce-placeholder',
    enforce: 'post',
    transformIndexHtml(html) {
      return html
        .replace(/<script(?![^>]*nonce=)/g, '<script nonce="__CSP_NONCE__"')
        .replace(/<link([^>]*rel="stylesheet")/g, '<link nonce="__CSP_NONCE__"$1')
    },
  }
}

// Build-time constants for reproducible builds (Epic 79)
// CI sets SOURCE_DATE_EPOCH from git commit timestamp; dev builds use current time
const buildTime = process.env.SOURCE_DATE_EPOCH
  ? new Date(parseInt(process.env.SOURCE_DATE_EPOCH) * 1000).toISOString()
  : new Date().toISOString()
const buildCommit = process.env.GITHUB_SHA || 'dev'
const buildVersion = JSON.parse(readFileSync('./package.json', 'utf-8')).version

export default defineConfig(({ mode }) => ({
  plugins: [
    tanstackRouter({
      target: 'react',
      autoCodeSplitting: true,
      routesDirectory: './src/client/routes',
      generatedRouteTree: './src/client/routeTree.gen.ts',
    }),
    react(),
    tailwindcss(),
    VitePWA({
      strategies: 'injectManifest',
      srcDir: 'src/client',
      filename: 'service-worker.ts',
      registerType: 'prompt',
      includeAssets: ['favicon.svg', 'apple-touch-icon.svg'],
      manifest: {
        name: 'Hotline',
        short_name: 'Hotline',
        description: 'Secure communication app',
        theme_color: '#1a1a2e',
        background_color: '#0a0a0a',
        display: 'standalone',
        orientation: 'portrait',
        scope: '/',
        start_url: '/',
        icons: [
          {
            src: 'pwa-192x192.svg',
            sizes: '192x192',
            type: 'image/svg+xml',
          },
          {
            src: 'pwa-512x512.svg',
            sizes: '512x512',
            type: 'image/svg+xml',
            purpose: 'any maskable',
          },
        ],
      },
      injectManifest: {
        globPatterns: ['**/*.{js,css,html,svg,woff2}'],
        // No API runtime caching — sensitive call data must never be cached on device
      },
    }),
    sriWorkboxPlugin(),
    cspNoncePlaceholderPlugin(),
    coreCryptoWasmPlugin(),
  ],
  root: '.',
  publicDir: 'public',
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src/client'),
      '@shared': path.resolve(__dirname, './src/shared'),
    },
    conditions: ['import', 'module', 'default'],
  },
  define: {
    '__BUILD_TIME__': JSON.stringify(buildTime),
    '__BUILD_COMMIT__': JSON.stringify(buildCommit),
    '__BUILD_VERSION__': JSON.stringify(buildVersion),
    '__PINNED_SIGNING_KEY__': JSON.stringify(process.env.VITE_RELEASE_SIGNING_PUBKEY || ''),
    '__API_ORIGIN__': JSON.stringify(process.env.VITE_API_ORIGIN || ''),
  },
  build: {
    outDir: 'dist/client',
    emptyOutDir: true,
    ...(mode === 'production' && {
      rolldownOptions: {
        output: {
          minify: {
            compress: {
              dropConsole: true,
              dropDebugger: true,
            },
          },
        },
      },
    }),
  },
}))
