// Tier 4 PR-B — postMessage RPC protocol between the main app frame and the
// sandboxed crypto iframe. Every message crossing the boundary is parsed
// against these schemas before any handler runs. A schema violation aborts
// the dispatch and (on the iframe side) increments the anomaly counter.
//
// See docs/superpowers/specs/2026-04-10-security-tier-4-delivery-hardening-design.md §4.2.3.

// NOTE: this schema is never served over HTTP — it's a postMessage contract
// between the main SPA frame and the sandboxed crypto iframe. Importing
// plain `zod` (not `@hono/zod-openapi`) keeps the iframe bundle from pulling
// in Hono. The iframe bundle must stay small (< 100 KiB gzipped) so it
// boots instantly.
import { z } from 'zod'

const Uuid = z.string().uuid()
const Hex = (lenSpec?: { exactHex?: number }) =>
  lenSpec?.exactHex !== undefined
    ? z.string().regex(new RegExp(`^[0-9a-f]{${lenSpec.exactHex}}$`))
    : z.string().regex(/^[0-9a-f]+$/)

/**
 * Per-request request nonce (32 random bytes, hex-encoded).
 *
 * Rationale (see docs/security/TIER_4_POST_REVIEW.md §C-3 and
 * docs/security/TIER_5_POST_REVIEW.md): the crypto sandbox iframe is
 * mounted with `sandbox="allow-scripts"` (no `allow-same-origin`), which
 * gives it an opaque origin. Both sides therefore observe
 * `ev.origin === "null"` on every message, so origin-string matching alone
 * cannot distinguish a genuine sandbox reply from a same-origin attacker
 * who manages to post into the parent's window.
 *
 * To close that gap without weakening the sandbox, every RPC request
 * carries a 32-byte nonce generated by the parent. The iframe echoes the
 * same nonce on its response. The parent stores outstanding nonces in a
 * Map keyed by request id inside its own closure; any response whose
 * nonce does not match the stored value is dropped. The nonce never
 * leaves the parent's closure, so an attacker who can only observe
 * ev.data (not the parent's module state) has no way to forge a valid
 * response.
 */
const RequestNonceHex = Hex({ exactHex: 64 })

export const CryptoRpcEnvelopeSchema = z.object({
  v: z.literal(2),
  labelId: z.number().int().min(0).max(255),
  wrappedKey: Hex(),
  ephemeralPubkey: Hex({ exactHex: 66 }),
  payload: Hex().optional(),
})
type CryptoRpcEnvelope = z.infer<typeof CryptoRpcEnvelopeSchema>

export const CryptoRpcRequestSchema = z.discriminatedUnion('op', [
  z.object({
    op: z.literal('unlock'),
    id: Uuid,
    nonceHex: RequestNonceHex,
    kekHex: Hex({ exactHex: 64 }),
    unlockNonceHex: Hex({ exactHex: 48 }),
    ciphertextHex: Hex(),
  }),
  z.object({
    op: z.literal('lock'),
    id: Uuid,
    nonceHex: RequestNonceHex,
  }),
  z.object({
    op: z.literal('decryptEnvelope'),
    id: Uuid,
    nonceHex: RequestNonceHex,
    envelope: CryptoRpcEnvelopeSchema,
    expectedLabel: z.string(),
    recordId: z.string().optional(),
  }),
  z.object({
    op: z.literal('decryptHubField'),
    id: Uuid,
    nonceHex: RequestNonceHex,
    hubId: Uuid,
    ciphertextHex: Hex(),
    recordId: z.string(),
    fieldName: z.string().regex(/^[a-zA-Z_][a-zA-Z0-9_]*$/),
  }),
  z.object({
    op: z.literal('encryptHubField'),
    id: Uuid,
    nonceHex: RequestNonceHex,
    hubId: Uuid,
    // 64 KiB cap prevents a runaway decrypt-loop from DoSing the iframe.
    plaintext: z.string().max(64 * 1024),
    recordId: z.string(),
    fieldName: z.string().regex(/^[a-zA-Z_][a-zA-Z0-9_]*$/),
  }),
  z.object({
    op: z.literal('signAuditEntry'),
    id: Uuid,
    nonceHex: RequestNonceHex,
    entryHashHex: Hex({ exactHex: 64 }),
  }),
  z.object({
    op: z.literal('rotateHubKey'),
    id: Uuid,
    nonceHex: RequestNonceHex,
    hubId: Uuid,
    expectedTriggerEntryHash: Hex({ exactHex: 64 }),
  }),
  z.object({
    op: z.literal('getPublicKey'),
    id: Uuid,
    nonceHex: RequestNonceHex,
  }),
  z.object({
    op: z.literal('isUnlocked'),
    id: Uuid,
    nonceHex: RequestNonceHex,
  }),
  z.object({
    op: z.literal('reportBundleHash'),
    id: Uuid,
    nonceHex: RequestNonceHex,
    hashHex: Hex({ exactHex: 64 }),
    timestamp: z.number().int(),
  }),
])
export type CryptoRpcRequest = z.infer<typeof CryptoRpcRequestSchema>

export const CryptoRpcErrorCodeSchema = z.enum([
  'schema_invalid',
  'locked',
  'label_mismatch',
  'aad_mismatch',
  'rate_limited',
  'chain_unverified',
  'unknown_hub',
  'internal',
])
export type CryptoRpcErrorCode = z.infer<typeof CryptoRpcErrorCodeSchema>

export const CryptoRpcSuccessSchema = z.object({
  kind: z.literal('success'),
  id: Uuid,
  /**
   * Echo of the request's 32-byte nonce. See the `RequestNonceHex` comment
   * above. The parent verifies the echoed nonce against the stored
   * outstanding-request nonce before resolving the pending call. Responses
   * whose nonce does not match are dropped silently — they are either
   * replays, stale responses to a destroyed call, or forgeries from a
   * same-origin attacker.
   */
  nonceHex: RequestNonceHex,
  result: z.unknown(),
})

export const CryptoRpcErrorSchema = z.object({
  kind: z.literal('error'),
  id: Uuid,
  /** See CryptoRpcSuccessSchema.nonceHex. Required on error responses too. */
  nonceHex: RequestNonceHex,
  code: CryptoRpcErrorCodeSchema,
  message: z.string(),
})

export const CryptoRpcResponseSchema = z.union([CryptoRpcSuccessSchema, CryptoRpcErrorSchema])
export type CryptoRpcResponse = z.infer<typeof CryptoRpcResponseSchema>

export const CryptoRpcReadySchema = z.object({
  kind: z.literal('ready'),
  protocol: z.literal(1),
})
type CryptoRpcReady = z.infer<typeof CryptoRpcReadySchema>
