/**
 * Downloads the EFF large wordlist and embeds it as a TypeScript module.
 *
 *   bun run scripts/generate-eff-wordlist.ts
 *
 * The wordlist is served from https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt
 * in the canonical Diceware format: "11111\tword\n11112\tword\n...". We drop the
 * dice-index column and emit a 7776-entry string array. The SHA-256 of the final
 * text is asserted against a constant so any tampering during download is
 * detected at build time.
 */
import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'

const URL = 'https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt'
const EXPECTED_SHA256 = 'addd35536511597a02fa0a9ff1e5284677b8883b83e986e43f15a3db996b903e'

async function main() {
  const res = await fetch(URL)
  if (!res.ok) throw new Error(`download failed: ${res.status}`)
  const text = await res.text()
  const hash = createHash('sha256').update(text).digest('hex')
  if (hash !== EXPECTED_SHA256) {
    throw new Error(`EFF wordlist SHA-256 mismatch: ${hash} !== ${EXPECTED_SHA256}`)
  }
  const lines = text.split('\n').filter((l) => l.trim().length > 0)
  if (lines.length !== 7776) throw new Error(`expected 7776 words, got ${lines.length}`)
  const words: string[] = []
  for (const line of lines) {
    const [, word] = line.split(/\s+/)
    if (!word) throw new Error(`bad line: ${line}`)
    words.push(word)
  }
  const out = `/**
 * EFF large Diceware wordlist — 7776 entries, ~12.9 bits/word.
 * Auto-generated by scripts/generate-eff-wordlist.ts; do not edit by hand.
 * Source: https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt
 */
export const EFF_LARGE_WORDLIST = [
${words.map((w) => `  '${w}'`).join(',\n')},
] as const

export const EFF_LARGE_WORDLIST_SHA256 = '${EXPECTED_SHA256}' as const
`
  writeFileSync('src/client/assets/eff-large-wordlist.ts', out)
  process.stdout.write(`Wrote ${words.length} words to src/client/assets/eff-large-wordlist.ts\n`)
}

main().catch((err) => {
  process.stderr.write(`${err}\n`)
  process.exit(1)
})
