// Build-time constants injected by Vite (Epic 79: Reproducible Builds)
// CI sets these from SOURCE_DATE_EPOCH and GITHUB_SHA; dev builds use defaults
declare const __BUILD_TIME__: string
declare const __BUILD_COMMIT__: string
declare const __BUILD_VERSION__: string

// Type stub for the WASM crypto module (packages/crypto/dist/wasm/llamenos_core).
// The actual module is generated by wasm-pack and gitignored. This stub provides
// the TypeScript shape so tsc can type-check platform.ts without a WASM build.
declare module '*/llamenos_core' {
  interface KeypairResult {
    skHex: string
    pubkeyHex: string
    nsec: string
    npub: string
  }

  interface KeyEnvelope {
    [x: string]: unknown
    wrappedKey: string
    ephemeralPubkey: string
  }

  interface RecipientEnvelope {
    [x: string]: unknown
    pubkey: string
    wrappedKey: string
    ephemeralPubkey: string
  }

  interface EncryptedNoteResult {
    encryptedContent: string
    authorEnvelope: KeyEnvelope
    adminEnvelopes: RecipientEnvelope[]
  }

  interface EncryptedMessageResult {
    encryptedContent: string
    readerEnvelopes: RecipientEnvelope[]
  }

  interface ProvisioningEncryptResult {
    encryptedHex: string
    sasCode: string
  }

  interface ProvisioningDecryptResult {
    nsec: string
    sasCode: string
  }

  interface SignedNostrEvent {
    id: string
    pubkey: string
    created_at: number
    kind: number
    tags: string[][]
    content: string
    sig: string
  }

  export class WasmCryptoState {
    getPublicKey(): string
    createAuthToken(method: string, path: string): unknown
    eciesUnwrapKey(envelope: string, label: string): string
    encryptNote(payloadJson: string, authorPubkey: string, adminPubkeys: string): EncryptedNoteResult
    decryptNote(encryptedContent: string, envelope: string): string
    decryptLegacyNote(packed: string): string
    encryptMessage(plaintext: string, readerPubkeys: string): EncryptedMessageResult
    decryptMessage(encryptedContent: string, readerEnvelopes: string): string
    decryptCallRecord(encryptedContent: string, adminEnvelopes: string): string
    decryptTranscription(packed: string, ephemeralPubkeyHex: string): string
    encryptDraft(plaintext: string): string
    decryptDraft(packed: string): string
    encryptExport(jsonString: string): string
    signNostrEvent(eventJson: string): SignedNostrEvent
    decryptFileMetadata(encryptedContentHex: string, envelope: string): string
    unwrapFileKey(envelope: string): string
    unwrapHubKey(envelope: string): string
    rewrapFileKey(envelope: string, newRecipientPubkeyHex: string): RecipientEnvelope
    encryptNsecForProvisioning(ephemeralPubkeyHex: string): ProvisioningEncryptResult
    decryptProvisionedNsec(encryptedHex: string, primaryPubkeyHex: string, ephemeralSkHex: string): ProvisioningDecryptResult
    requestProvisioningToken(): string
    getNsec(token: string): string
    importKey(nsec: string, pin: string): unknown
    unlockWithPin(dataJson: string, pin: string): string
    lock(): void
    isUnlocked(): boolean
  }

  export function generateKeypair(): KeypairResult
  export function getPublicKeyFromSecret(secretKeyHex: string): string
  export function createAuthTokenStateless(secretKeyHex: string, method: string, path: string): unknown
  export function eciesWrapKey(keyHex: string, recipientPubkey: string, label: string): KeyEnvelope
  export function isValidNsec(nsec: string): boolean
  export function keyPairFromNsec(nsec: string): KeypairResult
  export function verifySchnorr(message: string, signature: string, pubkey: string): boolean
  export default function init(): Promise<void>
}
