/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkDeviceRouteImport } from './routes/link-device'
import { Route as IntakesRouteImport } from './routes/intakes'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as BlastsRouteImport } from './routes/blasts'
import { Route as BansRouteImport } from './routes/bans'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersPubkeyRouteImport } from './routes/users_.$pubkey'
import { Route as SecuritySessionsRouteImport } from './routes/security.sessions'
import { Route as SecurityPasskeysRouteImport } from './routes/security.passkeys'
import { Route as SecurityHistoryRouteImport } from './routes/security.history'
import { Route as SecurityFactorsRouteImport } from './routes/security.factors'
import { Route as NotesNoteIdRouteImport } from './routes/notes_.$noteId'
import { Route as ContactsContactIdRouteImport } from './routes/contacts_.$contactId'
import { Route as CallsCallIdRouteImport } from './routes/calls.$callId'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSectionRouteImport } from './routes/admin/$section'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkDeviceRoute = LinkDeviceRouteImport.update({
  id: '/link-device',
  path: '/link-device',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakesRoute = IntakesRouteImport.update({
  id: '/intakes',
  path: '/intakes',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const BlastsRoute = BlastsRouteImport.update({
  id: '/blasts',
  path: '/blasts',
  getParentRoute: () => rootRouteImport,
} as any)
const BansRoute = BansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UsersPubkeyRoute = UsersPubkeyRouteImport.update({
  id: '/users_/$pubkey',
  path: '/users/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuritySessionsRoute = SecuritySessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityPasskeysRoute = SecurityPasskeysRouteImport.update({
  id: '/passkeys',
  path: '/passkeys',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityHistoryRoute = SecurityHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityFactorsRoute = SecurityFactorsRouteImport.update({
  id: '/factors',
  path: '/factors',
  getParentRoute: () => SecurityRoute,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes_/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts_/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsCallIdRoute = CallsCallIdRouteImport.update({
  id: '/$callId',
  path: '/$callId',
  getParentRoute: () => CallsRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/conversations': typeof ConversationsRoute
  '/help': typeof HelpRoute
  '/intakes': typeof IntakesRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/users': typeof UsersRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/security/factors': typeof SecurityFactorsRoute
  '/security/history': typeof SecurityHistoryRoute
  '/security/passkeys': typeof SecurityPasskeysRoute
  '/security/sessions': typeof SecuritySessionsRoute
  '/users/$pubkey': typeof UsersPubkeyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/conversations': typeof ConversationsRoute
  '/help': typeof HelpRoute
  '/intakes': typeof IntakesRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/users': typeof UsersRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/security/factors': typeof SecurityFactorsRoute
  '/security/history': typeof SecurityHistoryRoute
  '/security/passkeys': typeof SecurityPasskeysRoute
  '/security/sessions': typeof SecuritySessionsRoute
  '/users/$pubkey': typeof UsersPubkeyRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/audit': typeof AuditRoute
  '/bans': typeof BansRoute
  '/blasts': typeof BlastsRoute
  '/calls': typeof CallsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/conversations': typeof ConversationsRoute
  '/help': typeof HelpRoute
  '/intakes': typeof IntakesRoute
  '/link-device': typeof LinkDeviceRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shifts': typeof ShiftsRoute
  '/users': typeof UsersRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/contacts_/$contactId': typeof ContactsContactIdRoute
  '/notes_/$noteId': typeof NotesNoteIdRoute
  '/security/factors': typeof SecurityFactorsRoute
  '/security/history': typeof SecurityHistoryRoute
  '/security/passkeys': typeof SecurityPasskeysRoute
  '/security/sessions': typeof SecuritySessionsRoute
  '/users_/$pubkey': typeof UsersPubkeyRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/contacts'
    | '/conversations'
    | '/help'
    | '/intakes'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/security'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/users'
    | '/admin/$section'
    | '/admin/settings'
    | '/calls/$callId'
    | '/contacts/$contactId'
    | '/notes/$noteId'
    | '/security/factors'
    | '/security/history'
    | '/security/passkeys'
    | '/security/sessions'
    | '/users/$pubkey'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/contacts'
    | '/conversations'
    | '/help'
    | '/intakes'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/security'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/users'
    | '/admin/$section'
    | '/admin/settings'
    | '/calls/$callId'
    | '/contacts/$contactId'
    | '/notes/$noteId'
    | '/security/factors'
    | '/security/history'
    | '/security/passkeys'
    | '/security/sessions'
    | '/users/$pubkey'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/bans'
    | '/blasts'
    | '/calls'
    | '/contacts'
    | '/conversations'
    | '/help'
    | '/intakes'
    | '/link-device'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/preferences'
    | '/profile-setup'
    | '/reports'
    | '/security'
    | '/settings'
    | '/setup'
    | '/shifts'
    | '/users'
    | '/admin/$section'
    | '/admin/settings'
    | '/calls/$callId'
    | '/contacts_/$contactId'
    | '/notes_/$noteId'
    | '/security/factors'
    | '/security/history'
    | '/security/passkeys'
    | '/security/sessions'
    | '/users_/$pubkey'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuditRoute: typeof AuditRoute
  BansRoute: typeof BansRoute
  BlastsRoute: typeof BlastsRoute
  CallsRoute: typeof CallsRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  ConversationsRoute: typeof ConversationsRoute
  HelpRoute: typeof HelpRoute
  IntakesRoute: typeof IntakesRoute
  LinkDeviceRoute: typeof LinkDeviceRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  ReportsRoute: typeof ReportsRoute
  SecurityRoute: typeof SecurityRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShiftsRoute: typeof ShiftsRoute
  UsersRoute: typeof UsersRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  UsersPubkeyRoute: typeof UsersPubkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-device': {
      id: '/link-device'
      path: '/link-device'
      fullPath: '/link-device'
      preLoaderRoute: typeof LinkDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intakes': {
      id: '/intakes'
      path: '/intakes'
      fullPath: '/intakes'
      preLoaderRoute: typeof IntakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blasts': {
      id: '/blasts'
      path: '/blasts'
      fullPath: '/blasts'
      preLoaderRoute: typeof BlastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bans': {
      id: '/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof BansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/users_/$pubkey': {
      id: '/users_/$pubkey'
      path: '/users/$pubkey'
      fullPath: '/users/$pubkey'
      preLoaderRoute: typeof UsersPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/sessions': {
      id: '/security/sessions'
      path: '/sessions'
      fullPath: '/security/sessions'
      preLoaderRoute: typeof SecuritySessionsRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/passkeys': {
      id: '/security/passkeys'
      path: '/passkeys'
      fullPath: '/security/passkeys'
      preLoaderRoute: typeof SecurityPasskeysRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/history': {
      id: '/security/history'
      path: '/history'
      fullPath: '/security/history'
      preLoaderRoute: typeof SecurityHistoryRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/factors': {
      id: '/security/factors'
      path: '/factors'
      fullPath: '/security/factors'
      preLoaderRoute: typeof SecurityFactorsRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/notes_/$noteId': {
      id: '/notes_/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts_/$contactId': {
      id: '/contacts_/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$callId': {
      id: '/calls/$callId'
      path: '/$callId'
      fullPath: '/calls/$callId'
      preLoaderRoute: typeof CallsCallIdRouteImport
      parentRoute: typeof CallsRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CallsRouteChildren {
  CallsCallIdRoute: typeof CallsCallIdRoute
}

const CallsRouteChildren: CallsRouteChildren = {
  CallsCallIdRoute: CallsCallIdRoute,
}

const CallsRouteWithChildren = CallsRoute._addFileChildren(CallsRouteChildren)

interface SecurityRouteChildren {
  SecurityFactorsRoute: typeof SecurityFactorsRoute
  SecurityHistoryRoute: typeof SecurityHistoryRoute
  SecurityPasskeysRoute: typeof SecurityPasskeysRoute
  SecuritySessionsRoute: typeof SecuritySessionsRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityFactorsRoute: SecurityFactorsRoute,
  SecurityHistoryRoute: SecurityHistoryRoute,
  SecurityPasskeysRoute: SecurityPasskeysRoute,
  SecuritySessionsRoute: SecuritySessionsRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuditRoute: AuditRoute,
  BansRoute: BansRoute,
  BlastsRoute: BlastsRoute,
  CallsRoute: CallsRouteWithChildren,
  ContactsRoute: ContactsRoute,
  ConversationsRoute: ConversationsRoute,
  HelpRoute: HelpRoute,
  IntakesRoute: IntakesRoute,
  LinkDeviceRoute: LinkDeviceRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  ReportsRoute: ReportsRoute,
  SecurityRoute: SecurityRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShiftsRoute: ShiftsRoute,
  UsersRoute: UsersRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  UsersPubkeyRoute: UsersPubkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
